### PR TITLE
initial implementation of BCRYPTHasher with unit test

### PR DESCRIPTION
**Pull request by cl0secall**
based on tag 1.4.5. adds BCRYPTHasher to modoboa.core.password_hashers.advanced, along with necessary glue. This implementation fixes "rounds" at 12.

### CODE REVIEW

**Comment by tonioo** [comment]
Thank you! To let users define a round level different than 12, we need to find a way to limit the value per hasher. I think it can be done later. Have you check what happen when you try to use this hasher on a Linux platform ?
Otherwise, could you please update the corresponding unit test (modoboa/admin/tests/test_password_schemes.py) and so increase the coverage level of your PR ?

**Comment by tonioo** [comment]
@cl0secall Any news about the coverage? :)

**Comment by cl0secall** [comment]
unit test added, plus naming fixes so the test actually passes.

**Comment by tonioo** [comment]
@cl0secall Great! Unfortunately, I made changes to master so now your branch can't be merged automatically :(
I'll try to update it but I don't know if I can easily.

**Pull request merged**
