### PR TITLE
Append imaputils to modoboa main repository

### PR DESCRIPTION
**Pull request by harobed**
Fix https://github.com/modoboa/modoboa-sievefilters/issues/4 append imaputils to modoboa main repository

### CODE REVIEW

**Comment by harobed** [comment]
I've removed useless method in imaputils. Tested on my instanace with sievefilter

**Comment by tonioo** [comment]
Actually, moving those modules into the core application is not a really good idea. Parameters are splitted between applications (core and webmail), this is not consistent... You also need to migrate existing parameters (rename them from modoboa_webmail.XXX to core.XXX)

Other issue: people who don't use the webmail and the sieve module will see useless IMAP parameters. I definitely think this is not the right place.

Maybe a cleaner solution would be to create a dedicated library (modoboa_imap_library?) for that ?

**Comment by harobed** [comment]
> Other issue: people who don't use the webmail and the sieve module will see useless IMAP parameters. I definitely think this is not the right place.

I understand, what is a best solution ? append this imap_utils in modoboa_sievefilters ?

**Comment by harobed** [comment]
> Maybe a cleaner solution would be to create a dedicated library (modoboa_imap_library?) for that ?

If we create too many small libs, I think that modoboa will become a kludge.

**Comment by tonioo** [comment]
Indeed... I don't know what to do right now. If we copy the modules into the sieve extensions, we will have to configure IMAP parameters twice (webmail and sieve).

**Comment by harobed** [comment]
>  If we copy the modules into the sieve extensions, we will have to configure IMAP parameters twice (webmail and sieve).

Now, it's can be a good compromise.

**Comment by tonioo** [comment]
Finally, I think you're right. Users will have to configure IMAP settings twice.
Anyway, we don't have to put the fetch_parser.py file into the core application since it is only used by the webmail. I will split this part.

**Pull request merged**
